import type { Vulnerability } from "./types"

export const mockVulnerabilities: Vulnerability[] = [
  {
    id: "1",
    cveId: "CVE-2024-38213",
    status: "Awaiting Disposition",
    system: "Payment Gateway Service",
    severity: "Critical",
    description:
      "A remote code execution vulnerability exists in the authentication module that could allow an attacker to execute arbitrary code with elevated privileges. This affects all versions prior to 2.4.1.",
    firstDetected: new Date("2024-11-15"),
    cvssScore: 9.8,
    activityLog: [
      {
        id: "1",
        userName: "System",
        action: "created vulnerability record",
        timestamp: new Date("2024-11-15T09:00:00"),
      },
    ],
  },
  {
    id: "2",
    cveId: "CVE-2024-42156",
    status: "In Progress",
    system: "Customer Portal API",
    severity: "High",
    disposition: "Fix",
    crqNumber: "CRQ000000123456",
    owner: { name: "John Smith" },
    expectedFixDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    description:
      "SQL injection vulnerability in the search functionality allows authenticated users to extract sensitive data from the database through crafted input parameters.",
    firstDetected: new Date("2024-11-10"),
    cvssScore: 8.1,
    ctiRemediation: true,
    requestedPatchWindow: "Sat 5/9 00:00–08:00 ET",
    identifiedBlockers: ["Testing and partner / peer team dependencies"],
    expectedRemediationDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    activityLog: [
      {
        id: "1",
        userName: "System",
        action: "created vulnerability record",
        timestamp: new Date("2024-11-10T10:00:00"),
      },
      {
        id: "2",
        userName: "John Smith",
        action: "set",
        field: "Disposition",
        value: "Fix",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      },
      {
        id: "3",
        userName: "John Smith",
        action: "added",
        field: "CRQ",
        value: "CRQ000000123456",
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "3",
    cveId: "CVE-2024-35218",
    status: "Pending Clear Scan",
    system: "Internal Messaging Service",
    severity: "Medium",
    disposition: "Fix",
    crqNumber: "CRQ000000789012",
    owner: { name: "Sarah Johnson" },
    expectedFixDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    description:
      "Cross-site scripting (XSS) vulnerability in the message rendering component allows injection of malicious scripts through specially crafted messages.",
    firstDetected: new Date("2024-11-01"),
    cvssScore: 6.1,
    ctiRemediation: true,
    requestedPatchWindow: "Sun 5/10 00:00–08:00 ET",
    expectedRemediationDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    remediationComplete: true,
    healthCheckTime: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    activityLog: [
      {
        id: "1",
        userName: "System",
        action: "created vulnerability record",
        timestamp: new Date("2024-11-01T08:00:00"),
      },
      {
        id: "2",
        userName: "Sarah Johnson",
        action: "set",
        field: "Disposition",
        value: "Fix",
        timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000),
      },
      {
        id: "3",
        userName: "Sarah Johnson",
        action: "marked",
        field: "Remediation Complete",
        value: "Yes",
        timestamp: new Date(Date.now() - 30 * 60 * 1000),
      },
    ],
  },
  {
    id: "4",
    cveId: "CVE-2024-29847",
    status: "Resolved",
    system: "Transaction Processor",
    severity: "High",
    disposition: "Fix",
    crqNumber: "CRQ000000345678",
    owner: { name: "Mike Davis" },
    description:
      "Buffer overflow vulnerability in the transaction parsing module could lead to denial of service or potential code execution.",
    firstDetected: new Date("2024-10-20"),
    cvssScore: 7.5,
    ctiRemediation: true,
    requestedPatchWindow: "Sat 5/9 08:00–16:00 ET",
    expectedRemediationDate: new Date("2024-11-05"),
    remediationComplete: true,
    healthCheckTime: new Date("2024-11-06T10:00:00"),
    healthCheckComplete: true,
    activityLog: [
      {
        id: "1",
        userName: "System",
        action: "created vulnerability record",
        timestamp: new Date("2024-10-20T14:00:00"),
      },
      {
        id: "2",
        userName: "Mike Davis",
        action: "set",
        field: "Disposition",
        value: "Fix",
        timestamp: new Date("2024-10-25T09:00:00"),
      },
      {
        id: "3",
        userName: "Mike Davis",
        action: "marked",
        field: "Health Check Complete",
        value: "Yes",
        timestamp: new Date("2024-11-06T10:00:00"),
      },
    ],
  },
  {
    id: "5",
    cveId: "CVE-2024-31982",
    status: "Awaiting Disposition",
    system: "Fraud Detection Engine",
    severity: "Critical",
    description:
      "Authentication bypass vulnerability allows unauthenticated access to admin functions through manipulated JWT tokens.",
    firstDetected: new Date("2024-11-18"),
    cvssScore: 9.1,
    activityLog: [
      {
        id: "1",
        userName: "System",
        action: "created vulnerability record",
        timestamp: new Date("2024-11-18T11:00:00"),
      },
    ],
  },
  {
    id: "6",
    cveId: "CVE-2024-28995",
    status: "In Progress",
    system: "Account Management Service",
    severity: "Low",
    disposition: "Accept Risk",
    owner: { name: "Emily Chen" },
    description:
      "Information disclosure vulnerability in error messages may reveal internal system paths and configuration details.",
    firstDetected: new Date("2024-11-05"),
    cvssScore: 3.7,
    ctiRemediation: false,
    identifiedBlockers: [
      "Application re-design / re-architecture required",
      "Third-party dependencies",
    ],
    expectedRemediationDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    activityLog: [
      {
        id: "1",
        userName: "System",
        action: "created vulnerability record",
        timestamp: new Date("2024-11-05T16:00:00"),
      },
      {
        id: "2",
        userName: "Emily Chen",
        action: "set",
        field: "Disposition",
        value: "Accept Risk",
        timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "7",
    cveId: "CVE-2024-40711",
    status: "In Progress",
    system: "Mobile Banking Backend",
    severity: "High",
    disposition: "Mitigate",
    crqNumber: "CRQ000000567890",
    owner: { name: "David Wilson" },
    expectedFixDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    description:
      "Insecure deserialization vulnerability in the session handling mechanism could allow remote code execution.",
    firstDetected: new Date("2024-11-12"),
    cvssScore: 8.6,
    ctiRemediation: true,
    requestedPatchWindow: "Sat 5/9 16:00–00:00 ET",
    identifiedBlockers: [
      "Vendor / internal package availability",
      "Limited central (bulk) remediation capabilities",
    ],
    expectedRemediationDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    activityLog: [
      {
        id: "1",
        userName: "System",
        action: "created vulnerability record",
        timestamp: new Date("2024-11-12T13:00:00"),
      },
      {
        id: "2",
        userName: "David Wilson",
        action: "set",
        field: "Disposition",
        value: "Mitigate",
        timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "8",
    cveId: "CVE-2024-37085",
    status: "Pending Clear Scan",
    system: "Document Management System",
    severity: "Medium",
    disposition: "Fix",
    crqNumber: "CRQ000000901234",
    owner: { name: "Lisa Taylor" },
    expectedFixDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    description:
      "Path traversal vulnerability in the file upload functionality allows reading arbitrary files from the server.",
    firstDetected: new Date("2024-10-28"),
    cvssScore: 5.9,
    ctiRemediation: true,
    requestedPatchWindow: "Sun 5/10 08:00–16:00 ET",
    expectedRemediationDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    remediationComplete: true,
    healthCheckTime: new Date(Date.now() + 12 * 60 * 60 * 1000),
    activityLog: [
      {
        id: "1",
        userName: "System",
        action: "created vulnerability record",
        timestamp: new Date("2024-10-28T09:00:00"),
      },
      {
        id: "2",
        userName: "Lisa Taylor",
        action: "set",
        field: "Disposition",
        value: "Fix",
        timestamp: new Date(Date.now() - 96 * 60 * 60 * 1000),
      },
      {
        id: "3",
        userName: "Lisa Taylor",
        action: "marked",
        field: "Remediation Complete",
        value: "Yes",
        timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: "9",
    cveId: "CVE-2024-23334",
    status: "Awaiting Disposition",
    system: "Compliance Reporting Tool",
    severity: "Medium",
    description:
      "Server-side request forgery (SSRF) vulnerability in the report generation module allows access to internal network resources.",
    firstDetected: new Date("2024-11-19"),
    cvssScore: 6.5,
    activityLog: [
      {
        id: "1",
        userName: "System",
        action: "created vulnerability record",
        timestamp: new Date("2024-11-19T07:00:00"),
      },
    ],
  },
  {
    id: "10",
    cveId: "CVE-2024-45519",
    status: "Resolved",
    system: "Email Notification Service",
    severity: "Low",
    disposition: "False Positive",
    owner: { name: "Robert Brown" },
    description:
      "Reported vulnerability in email template rendering was determined to be a false positive after security review.",
    firstDetected: new Date("2024-11-08"),
    cvssScore: 2.3,
    ctiRemediation: false,
    activityLog: [
      {
        id: "1",
        userName: "System",
        action: "created vulnerability record",
        timestamp: new Date("2024-11-08T15:00:00"),
      },
      {
        id: "2",
        userName: "Robert Brown",
        action: "set",
        field: "Disposition",
        value: "False Positive",
        timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
    ],
  },
]

export const patchWindows = [
  "Sat 5/9 00:00–08:00 ET",
  "Sat 5/9 08:00–16:00 ET",
  "Sat 5/9 16:00–00:00 ET",
  "Sun 5/10 00:00–08:00 ET",
  "Sun 5/10 08:00–16:00 ET",
  "Sun 5/10 16:00–00:00 ET",
]

export const blockerOptions = [
  "Vendor / internal package availability",
  "Testing and partner / peer team dependencies",
  "Limited central (bulk) remediation capabilities",
  "Third-party dependencies",
  "Hardware dependencies",
  "Application re-design / re-architecture required",
  "Hosting Capacity",
  "No patch available",
  "False positives in Vulnerability and FOSS data",
  "Data and reporting limitations",
] as const
