import type {
  Vulnerability,
  TriageStatus,
  Severity,
  Disposition,
  OperatingEnvironment,
  VerificationStatus,
  Source,
  Blocker,
  ActivityLogEntry,
  CioTeam,
  User,
  SparklineDataPoint,
  SeverityStatusData,
} from "./types";

// CIO Teams
export const CIO_TEAMS: CioTeam[] = [
  { id: "1", name: "Payments Technology", code: "PAY" },
  { id: "2", name: "Trading Systems", code: "TRD" },
  { id: "3", name: "Risk & Compliance", code: "RSK" },
  { id: "4", name: "Consumer Banking", code: "CNB" },
  { id: "5", name: "Wealth Management", code: "WLT" },
];

// Patch windows for scheduling
export const patchWindows = [
  "Sat 5/9 00:00–08:00 ET",
  "Sat 5/9 08:00–16:00 ET",
  "Sun 5/10 00:00–08:00 ET",
  "Sun 5/10 08:00–16:00 ET",
  "Sat 5/16 00:00–08:00 ET",
  "Sat 5/16 08:00–16:00 ET",
];

// Blocker options for disposition
export const blockerOptions: Blocker[] = [
  "Vendor / internal package availability",
  "Testing and partner / peer team dependencies",
  "Limited central (bulk) remediation capabilities",
  "Third-party dependencies",
  "Hardware dependencies",
  "Application re-design / re-architecture required",
  "Hosting Capacity",
  "No patch available",
  "False positives in Vulnerability and FOSS data",
  "Data and reporting limitations",
];

// Users for assignments
export const USERS: User[] = [
  { id: "1", name: "Sarah Chen", email: "sarah.chen@bank.internal" },
  { id: "2", name: "James Wilson", email: "james.wilson@bank.internal" },
  { id: "3", name: "Maria Garcia", email: "maria.garcia@bank.internal" },
  { id: "4", name: "David Kim", email: "david.kim@bank.internal" },
  { id: "5", name: "Emily Johnson", email: "emily.johnson@bank.internal" },
  { id: "6", name: "Michael Brown", email: "michael.brown@bank.internal" },
  { id: "7", name: "Lisa Anderson", email: "lisa.anderson@bank.internal" },
  { id: "8", name: "Robert Taylor", email: "robert.taylor@bank.internal" },
];

// Generate sparkline data deterministically based on index
export function generateSparklineData(baseValue: number, days: number = 14): SparklineDataPoint[] {
  const data: SparklineDataPoint[] = [];
  // Use a fixed reference date for SSR/client consistency
  const baseDate = new Date("2026-05-08T00:00:00Z");
  
  for (let i = days - 1; i >= 0; i--) {
    const date = new Date(baseDate.getTime() - i * 24 * 60 * 60 * 1000);
    // Use deterministic variation based on index instead of Math.random()
    const variation = Math.floor(baseValue * 0.2 * Math.sin(i * 0.5));
    data.push({
      date: date.toISOString().split("T")[0],
      value: Math.max(0, baseValue + variation),
    });
  }
  
  return data;
}

export function generateSeverityStatusData(vulnerabilities: Vulnerability[]): SeverityStatusData[] {
  const severities: Severity[] = ["Critical", "High", "Medium", "Low"];
  
  return severities.map((severity) => {
    const filtered = vulnerabilities.filter((v) => v.severity === severity);
    return {
      severity,
      awaitingDisposition: filtered.filter((v) => v.status === "Awaiting Disposition").length,
      inProgress: filtered.filter((v) => v.status === "In Progress").length,
      pendingClearScan: filtered.filter((v) => v.status === "Pending Clear Scan").length,
      resolved: filtered.filter((v) => v.status === "Resolved").length,
    };
  });
}

// Static mock data - pre-generated to avoid hydration issues
export const mockVulnerabilities: Vulnerability[] = [
  {
    id: "vuln-001",
    gisId: "GIS-2026-000001",
    qualysId: "QID-10001",
    cve: "CVE-2024-38213",
    title: "Remote Code Execution in Authentication Module",
    status: "Awaiting Disposition",
    severity: "Critical",
    severityRisk: "Critical",
    cvssScore: 9.8,
    verificationStatus: "Verified",
    source: "Qualys",
    disposition: null,
    ctiRemediation: null,
    identifiedBlockers: [],
    hostName: "pay-gw-prd-001.bank.internal",
    fqdn: "pay-gw-prd-001.payments.bank.internal",
    osName: "Red Hat Enterprise Linux 8.6",
    osVersion: "8.6",
    ipAddresses: ["10.1.100.45", "10.1.100.46"],
    operatingEnvironment: "Production",
    hostingPlatform: "AWS",
    isPublicInternetAccessible: false,
    isDmz: false,
    isOnSite: true,
    tier: "Tier 1 Critical",
    securityZone: "Internal",
    applicationFullName: "Payments Gateway",
    cioDisplayName: "Payments Technology",
    techExecutive: "John Smith",
    techExecutiveContact: "john.smith@bank.internal",
    vulnOwner: "Sarah Chen",
    vulnOwnerEmail: "sarah.chen@bank.internal",
    runbookOwner: "Platform Engineering",
    financialHierarchy: "Technology > Payments > Core Processing",
    description: "A critical vulnerability exists in the authentication module that allows remote attackers to execute arbitrary code by exploiting improper input validation in the login request handler.",
    technicalDescription: "This vulnerability affects the core authentication mechanism and requires immediate attention.",
    technicalDetail: "CVE details indicate that the vulnerability can be exploited remotely without authentication.",
    vulnerabilityFindings: "Confirmed via automated scan and manual verification.",
    vulnerabilitySubcategory: "Authentication",
    technology: "Apache",
    technologyVersion: "2.4.41",
    dateObserved: new Date("2025-10-15"),
    dateLastSeen: new Date("2026-05-05"),
    hostLastSeen: new Date("2026-05-07"),
    daysOpen: 173,
    dueDate: new Date("2026-05-03"),
    pastDue: true,
    patchCategory: "Security Update",
    patchTitle: "Apache Security Update 2026-01",
    vendorRiskLevel: "Critical",
    gisExternalFlag: true,
    esmType: "Tier 1 Critical",
    isBuiltInHouse: false,
    workstream: "Vulnerability Management",
    activityLog: [
      { id: "log-001-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2025-10-15") },
    ],
  },
  {
    id: "vuln-002",
    gisId: "GIS-2026-000002",
    qualysId: "QID-10002",
    cve: "CVE-2024-42156",
    title: "SQL Injection in Search Functionality",
    status: "In Progress",
    severity: "High",
    severityRisk: "High",
    cvssScore: 8.1,
    verificationStatus: "Verified",
    source: "Qualys",
    disposition: "Fix",
    ctiRemediation: true,
    identifiedBlockers: [],
    crqNumber: "CRQ000001234567",
    hostName: "auth-svc-prd-003.bank.internal",
    fqdn: "auth-svc-prd-003.auth.bank.internal",
    osName: "Windows Server 2019",
    osVersion: "2019",
    ipAddresses: ["10.2.50.101"],
    operatingEnvironment: "Production",
    hostingPlatform: "Azure",
    isPublicInternetAccessible: false,
    isDmz: false,
    isOnSite: false,
    tier: "Tier 1 Critical",
    securityZone: "Internal",
    applicationFullName: "Authentication Service",
    cioDisplayName: "Payments Technology",
    techExecutive: "Jane Doe",
    techExecutiveContact: "jane.doe@bank.internal",
    vulnOwner: "James Wilson",
    vulnOwnerEmail: "james.wilson@bank.internal",
    runbookOwner: "Security Operations",
    financialHierarchy: "Technology > Identity > Authentication",
    description: "The search functionality is vulnerable to SQL injection attacks due to insufficient sanitization of user input parameters.",
    technicalDescription: "SQL injection via unsanitized search parameters.",
    technicalDetail: "Parameterized queries not used in search endpoint.",
    vulnerabilityFindings: "Confirmed via penetration testing.",
    vulnerabilitySubcategory: "Injection",
    technology: "Java",
    technologyVersion: "11.0.12",
    dateObserved: new Date("2025-11-10"),
    dateLastSeen: new Date("2026-05-06"),
    hostLastSeen: new Date("2026-05-08"),
    daysOpen: 180,
    dueDate: new Date("2026-05-13"),
    expectedRemediationDate: new Date("2026-05-10"),
    requestedPatchWindow: "Sat 5/9 00:00–08:00 ET",
    pastDue: false,
    patchCategory: "Hotfix",
    patchTitle: "Java Security Hotfix 2026-05",
    vendorRiskLevel: "High",
    gisExternalFlag: false,
    esmType: "Tier 1 Critical",
    isBuiltInHouse: true,
    workstream: "Vulnerability Management",
    activityLog: [
      { id: "log-002-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2025-11-10") },
      { id: "log-002-2", odiserId: "2", userName: "James Wilson", action: "was assigned as vulnerability owner", timestamp: new Date("2025-11-12") },
      { id: "log-002-3", odiserId: "2", userName: "James Wilson", action: "changed status", field: "status", oldValue: "Awaiting Disposition", newValue: "In Progress", timestamp: new Date("2025-11-15") },
      { id: "log-002-4", odiserId: "2", userName: "James Wilson", action: 'set disposition to "Fix"', field: "disposition", newValue: "Fix", timestamp: new Date("2025-11-15") },
    ],
  },
  {
    id: "vuln-003",
    gisId: "GIS-2026-000003",
    qualysId: "QID-10003",
    cve: "CVE-2024-35218",
    title: "Cross-Site Scripting in Message Rendering",
    status: "Pending Clear Scan",
    severity: "High",
    severityRisk: "High",
    cvssScore: 7.5,
    verificationStatus: "Pending Verification",
    source: "Qualys",
    disposition: "Fix",
    ctiRemediation: true,
    identifiedBlockers: [],
    crqNumber: "CRQ000007890123",
    remediationComplete: true,
    hostName: "portal-web-prd-002.bank.internal",
    fqdn: "portal-web-prd-002.customer.bank.internal",
    osName: "Ubuntu 20.04 LTS",
    osVersion: "20.04",
    ipAddresses: ["172.16.20.55"],
    operatingEnvironment: "Production",
    hostingPlatform: "AWS",
    isPublicInternetAccessible: true,
    isDmz: true,
    isOnSite: false,
    tier: "Tier 2 Important",
    securityZone: "DMZ",
    applicationFullName: "Customer Portal",
    cioDisplayName: "Payments Technology",
    techExecutive: "Robert Johnson",
    techExecutiveContact: "robert.johnson@bank.internal",
    vulnOwner: "Maria Garcia",
    vulnOwnerEmail: "maria.garcia@bank.internal",
    runbookOwner: "DevOps",
    financialHierarchy: "Technology > Customer > Portal",
    description: "Cross-site scripting vulnerability in the message rendering component allows attackers to inject malicious scripts.",
    technicalDescription: "XSS via unsanitized message content rendering.",
    technicalDetail: "User input not properly escaped before DOM insertion.",
    vulnerabilityFindings: "Confirmed via automated scan.",
    vulnerabilitySubcategory: "Configuration",
    technology: "Node.js",
    technologyVersion: "16.13.0",
    dateObserved: new Date("2025-12-01"),
    dateLastSeen: new Date("2026-05-04"),
    hostLastSeen: new Date("2026-05-07"),
    daysOpen: 189,
    dueDate: new Date("2026-05-10"),
    scheduledFixDate: new Date("2026-05-05"),
    remediatedDate: new Date("2026-05-05"),
    pastDue: false,
    patchCategory: "Security Update",
    patchTitle: "Node.js Security Update 2026-04",
    vendorRiskLevel: "High",
    gisExternalFlag: false,
    esmType: "Tier 2 Important",
    isBuiltInHouse: true,
    workstream: "Patch Management",
    activityLog: [
      { id: "log-003-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2025-12-01") },
      { id: "log-003-2", odiserId: "3", userName: "Maria Garcia", action: "was assigned as vulnerability owner", timestamp: new Date("2025-12-03") },
      { id: "log-003-3", odiserId: "3", userName: "Maria Garcia", action: "changed status", field: "status", oldValue: "Awaiting Disposition", newValue: "In Progress", timestamp: new Date("2025-12-05") },
      { id: "log-003-4", odiserId: "3", userName: "Maria Garcia", action: 'set disposition to "Fix"', field: "disposition", newValue: "Fix", timestamp: new Date("2025-12-05") },
      { id: "log-003-5", odiserId: "3", userName: "Maria Garcia", action: "changed status", field: "status", oldValue: "In Progress", newValue: "Pending Clear Scan", timestamp: new Date("2026-05-05") },
    ],
  },
  {
    id: "vuln-004",
    gisId: "GIS-2026-000004",
    qualysId: "QID-10004",
    cve: "CVE-2024-29847",
    title: "Buffer Overflow in Transaction Parsing",
    status: "Resolved",
    severity: "High",
    severityRisk: "High",
    cvssScore: 8.5,
    verificationStatus: "Verified",
    source: "Qualys",
    disposition: "Fix",
    ctiRemediation: true,
    identifiedBlockers: [],
    crqNumber: "CRQ000004567890",
    remediationComplete: true,
    healthCheckComplete: true,
    healthCheckTime: new Date("2026-05-01"),
    hostName: "trade-eng-prd-005.bank.internal",
    fqdn: "trade-eng-prd-005.trading.bank.internal",
    osName: "Red Hat Enterprise Linux 8.6",
    osVersion: "8.6",
    ipAddresses: ["10.1.100.88", "10.1.100.89"],
    operatingEnvironment: "Production",
    hostingPlatform: "On-Premise",
    isPublicInternetAccessible: false,
    isDmz: false,
    isOnSite: true,
    tier: "Tier 1 Critical",
    securityZone: "Restricted",
    applicationFullName: "Trade Settlement Engine",
    cioDisplayName: "Payments Technology",
    techExecutive: "John Smith",
    techExecutiveContact: "john.smith@bank.internal",
    vulnOwner: "David Kim",
    vulnOwnerEmail: "david.kim@bank.internal",
    runbookOwner: "Infrastructure",
    financialHierarchy: "Technology > Trading > Settlement",
    description: "A buffer overflow vulnerability in the transaction parsing module can be exploited by sending specially crafted data.",
    technicalDescription: "Buffer overflow via malformed transaction packets.",
    technicalDetail: "Input length validation missing in parser.",
    vulnerabilityFindings: "Confirmed via code review and fuzzing.",
    vulnerabilitySubcategory: "Memory",
    technology: "Tomcat",
    technologyVersion: "9.0.45",
    dateObserved: new Date("2026-01-15"),
    dateLastSeen: new Date("2026-04-25"),
    hostLastSeen: new Date("2026-05-06"),
    daysOpen: 17,
    dueDate: new Date("2026-02-15"),
    scheduledFixDate: new Date("2026-04-28"),
    remediatedDate: new Date("2026-04-28"),
    pastDue: false,
    patchCategory: "Cumulative Update",
    patchTitle: "Tomcat Security Update 2026-04",
    vendorRiskLevel: "High",
    gisExternalFlag: false,
    esmType: "Tier 1 Critical",
    isBuiltInHouse: false,
    workstream: "Vulnerability Management",
    activityLog: [
      { id: "log-004-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2026-01-15") },
      { id: "log-004-2", odiserId: "4", userName: "David Kim", action: "was assigned as vulnerability owner", timestamp: new Date("2026-01-17") },
      { id: "log-004-3", odiserId: "4", userName: "David Kim", action: "changed status", field: "status", oldValue: "Awaiting Disposition", newValue: "In Progress", timestamp: new Date("2026-01-20") },
      { id: "log-004-4", odiserId: "4", userName: "David Kim", action: 'set disposition to "Fix"', field: "disposition", newValue: "Fix", timestamp: new Date("2026-01-20") },
      { id: "log-004-5", odiserId: "4", userName: "David Kim", action: "changed status", field: "status", oldValue: "In Progress", newValue: "Pending Clear Scan", timestamp: new Date("2026-04-28") },
      { id: "log-004-6", odiserId: "4", userName: "David Kim", action: "marked health check as complete", timestamp: new Date("2026-05-01") },
      { id: "log-004-7", odiserId: "4", userName: "David Kim", action: "changed status", field: "status", oldValue: "Pending Clear Scan", newValue: "Resolved", timestamp: new Date("2026-05-01") },
    ],
  },
  {
    id: "vuln-005",
    gisId: "GIS-2026-000005",
    qualysId: "QID-10005",
    cve: "CVE-2024-31982",
    title: "Authentication Bypass via JWT Manipulation",
    status: "Awaiting Disposition",
    severity: "Critical",
    severityRisk: "Critical",
    cvssScore: 9.1,
    verificationStatus: "Verified",
    source: "Tenable",
    disposition: null,
    ctiRemediation: null,
    identifiedBlockers: [],
    hostName: "risk-rpt-prd-001.bank.internal",
    fqdn: "risk-rpt-prd-001.risk.bank.internal",
    osName: "Windows Server 2019",
    osVersion: "2019",
    ipAddresses: ["10.2.50.200"],
    operatingEnvironment: "Production",
    hostingPlatform: "Azure",
    isPublicInternetAccessible: false,
    isDmz: false,
    isOnSite: false,
    tier: "Tier 1 Critical",
    securityZone: "Internal",
    applicationFullName: "Risk Reporting Platform",
    cioDisplayName: "Payments Technology",
    techExecutive: "Patricia Williams",
    techExecutiveContact: "patricia.williams@bank.internal",
    vulnOwner: "Emily Johnson",
    vulnOwnerEmail: "emily.johnson@bank.internal",
    runbookOwner: "Security Operations",
    financialHierarchy: "Technology > Risk > Reporting",
    description: "The JWT validation process can be bypassed by manipulating the algorithm header, allowing attackers to forge tokens.",
    technicalDescription: "JWT algorithm confusion attack possible.",
    technicalDetail: "Server accepts 'none' algorithm in JWT header.",
    vulnerabilityFindings: "Confirmed via penetration testing.",
    vulnerabilitySubcategory: "Authentication",
    technology: "OpenSSL",
    technologyVersion: "1.1.1k",
    dateObserved: new Date("2025-10-20"),
    dateLastSeen: new Date("2026-05-07"),
    hostLastSeen: new Date("2026-05-08"),
    daysOpen: 171,
    dueDate: new Date("2026-05-11"),
    pastDue: false,
    patchCategory: "Security Update",
    patchTitle: "OpenSSL Security Update 2026-05",
    vendorRiskLevel: "Critical",
    gisExternalFlag: true,
    esmType: "Tier 1 Critical",
    isBuiltInHouse: false,
    workstream: "Vulnerability Management",
    activityLog: [
      { id: "log-005-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2025-10-20") },
      { id: "log-005-2", odiserId: "5", userName: "Emily Johnson", action: "was assigned as vulnerability owner", timestamp: new Date("2025-10-22") },
    ],
  },
  {
    id: "vuln-006",
    gisId: "GIS-2026-000006",
    qualysId: "QID-10006",
    cve: "CVE-2024-28995",
    title: "Information Disclosure in Error Messages",
    status: "In Progress",
    severity: "Low",
    severityRisk: "Low",
    cvssScore: 4.3,
    verificationStatus: "Verified",
    source: "Qualys",
    disposition: "Accept Risk",
    ctiRemediation: false,
    identifiedBlockers: ["Application re-design / re-architecture required"],
    crqNumber: "CRQ000033717852",
    hostName: "acct-mgmt-prd-002.bank.internal",
    fqdn: "acct-mgmt-prd-002.accounts.bank.internal",
    osName: "Red Hat Enterprise Linux 8.6",
    osVersion: "8.6",
    ipAddresses: ["10.1.100.150"],
    operatingEnvironment: "Production",
    hostingPlatform: "Private Cloud",
    isPublicInternetAccessible: false,
    isDmz: false,
    isOnSite: true,
    tier: "Tier 2 Important",
    securityZone: "Internal",
    applicationFullName: "Trade Settlement Engine",
    cioDisplayName: "Payments Technology",
    techExecutive: "Jane Doe",
    techExecutiveContact: "jane.doe@bank.internal",
    vulnOwner: "Michael Brown",
    vulnOwnerEmail: "michael.brown@bank.internal",
    runbookOwner: "Platform Engineering",
    financialHierarchy: "Technology > Trading > Settlement",
    description: "Error messages returned by the application disclose sensitive information about the internal system architecture.",
    technicalDescription: "Verbose error messages expose stack traces.",
    technicalDetail: "Debug mode enabled in production configuration.",
    vulnerabilityFindings: "Confirmed via manual testing.",
    vulnerabilitySubcategory: "Configuration",
    technology: "MySQL",
    technologyVersion: "8.0.27",
    dateObserved: new Date("2025-11-05"),
    dateLastSeen: new Date("2026-05-05"),
    hostLastSeen: new Date("2026-05-08"),
    daysOpen: 185,
    dueDate: new Date("2026-06-07"),
    expectedRemediationDate: new Date("2026-05-30"),
    pastDue: false,
    patchCategory: "Configuration Change",
    patchTitle: "MySQL Configuration Hardening",
    vendorRiskLevel: "Low",
    gisExternalFlag: false,
    esmType: "Tier 2 Important",
    isBuiltInHouse: true,
    workstream: "Risk Remediation",
    activityLog: [
      { id: "log-006-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2025-11-05") },
      { id: "log-006-2", odiserId: "6", userName: "Michael Brown", action: "was assigned as vulnerability owner", timestamp: new Date("2025-11-07") },
      { id: "log-006-3", odiserId: "6", userName: "Michael Brown", action: "changed status", field: "status", oldValue: "Awaiting Disposition", newValue: "In Progress", timestamp: new Date("2025-11-10") },
      { id: "log-006-4", odiserId: "6", userName: "Michael Brown", action: 'set disposition to "Accept Risk"', field: "disposition", newValue: "Accept Risk", timestamp: new Date("2025-11-10") },
    ],
  },
  {
    id: "vuln-007",
    gisId: "GIS-2026-000007",
    qualysId: "QID-10007",
    cve: "CVE-2024-48711",
    title: "Insecure Deserialization in Session Handling",
    status: "In Progress",
    severity: "High",
    severityRisk: "High",
    cvssScore: 8.8,
    verificationStatus: "Verified",
    source: "Qualys",
    disposition: "Mitigate",
    ctiRemediation: true,
    identifiedBlockers: [],
    crqNumber: "CRQ000008056789",
    hostName: "mobile-api-prd-004.bank.internal",
    fqdn: "mobile-api-prd-004.mobile.bank.internal",
    osName: "Ubuntu 20.04 LTS",
    osVersion: "20.04",
    ipAddresses: ["172.16.20.88"],
    operatingEnvironment: "Production",
    hostingPlatform: "GCP",
    isPublicInternetAccessible: true,
    isDmz: true,
    isOnSite: false,
    tier: "Tier 1 Critical",
    securityZone: "DMZ",
    applicationFullName: "Payments Gateway",
    cioDisplayName: "Payments Technology",
    techExecutive: "Robert Johnson",
    techExecutiveContact: "robert.johnson@bank.internal",
    vulnOwner: "Lisa Anderson",
    vulnOwnerEmail: "lisa.anderson@bank.internal",
    runbookOwner: "DevOps",
    financialHierarchy: "Technology > Payments > Mobile",
    description: "The session handling mechanism is vulnerable to insecure deserialization attacks.",
    technicalDescription: "Unsafe deserialization of session objects.",
    technicalDetail: "Java ObjectInputStream used without type filtering.",
    vulnerabilityFindings: "Confirmed via code review.",
    vulnerabilitySubcategory: "Injection",
    technology: "Nginx",
    technologyVersion: "1.18.0",
    dateObserved: new Date("2025-10-25"),
    dateLastSeen: new Date("2026-05-06"),
    hostLastSeen: new Date("2026-05-07"),
    daysOpen: 177,
    dueDate: new Date("2026-05-18"),
    expectedRemediationDate: new Date("2026-05-15"),
    requestedPatchWindow: "Sat 5/16 00:00–08:00 ET",
    pastDue: false,
    patchCategory: "Hotfix",
    patchTitle: "Session Handler Security Patch",
    vendorRiskLevel: "High",
    gisExternalFlag: false,
    esmType: "Tier 1 Critical",
    isBuiltInHouse: true,
    workstream: "Vulnerability Management",
    activityLog: [
      { id: "log-007-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2025-10-25") },
      { id: "log-007-2", odiserId: "7", userName: "Lisa Anderson", action: "was assigned as vulnerability owner", timestamp: new Date("2025-10-27") },
      { id: "log-007-3", odiserId: "7", userName: "Lisa Anderson", action: "changed status", field: "status", oldValue: "Awaiting Disposition", newValue: "In Progress", timestamp: new Date("2025-10-30") },
      { id: "log-007-4", odiserId: "7", userName: "Lisa Anderson", action: 'set disposition to "Mitigate"', field: "disposition", newValue: "Mitigate", timestamp: new Date("2025-10-30") },
    ],
  },
  {
    id: "vuln-008",
    gisId: "GIS-2026-000008",
    qualysId: "QID-10008",
    cve: "CVE-2024-37085",
    title: "Path Traversal in File Upload",
    status: "Pending Clear Scan",
    severity: "Medium",
    severityRisk: "Medium",
    cvssScore: 6.5,
    verificationStatus: "Verified",
    source: "Qualys",
    disposition: "Fix",
    ctiRemediation: true,
    identifiedBlockers: [],
    crqNumber: "CRQ000000081234",
    remediationComplete: true,
    hostName: "doc-mgmt-prd-001.bank.internal",
    fqdn: "doc-mgmt-prd-001.docs.bank.internal",
    osName: "Windows Server 2019",
    osVersion: "2019",
    ipAddresses: ["10.2.50.75"],
    operatingEnvironment: "Non-Production",
    hostingPlatform: "Azure",
    isPublicInternetAccessible: false,
    isDmz: false,
    isOnSite: false,
    tier: "Tier 3 Standard",
    securityZone: "Internal",
    applicationFullName: "Customer Portal",
    cioDisplayName: "Payments Technology",
    techExecutive: "Patricia Williams",
    techExecutiveContact: "patricia.williams@bank.internal",
    vulnOwner: "Robert Taylor",
    vulnOwnerEmail: "robert.taylor@bank.internal",
    runbookOwner: "Infrastructure",
    financialHierarchy: "Technology > Customer > Documents",
    description: "Path traversal vulnerability in the file upload functionality allows attackers to write files to arbitrary locations.",
    technicalDescription: "Directory traversal via filename manipulation.",
    technicalDetail: "Filename not sanitized before file write operation.",
    vulnerabilityFindings: "Confirmed via penetration testing.",
    vulnerabilitySubcategory: "Input Validation",
    technology: "PostgreSQL",
    technologyVersion: "13.4",
    dateObserved: new Date("2025-12-15"),
    dateLastSeen: new Date("2026-05-03"),
    hostLastSeen: new Date("2026-05-06"),
    daysOpen: 193,
    dueDate: new Date("2026-05-09"),
    scheduledFixDate: new Date("2026-05-04"),
    remediatedDate: new Date("2026-05-04"),
    pastDue: false,
    patchCategory: "Security Update",
    patchTitle: "File Upload Security Patch",
    vendorRiskLevel: "Medium",
    gisExternalFlag: false,
    esmType: "Tier 3 Standard",
    isBuiltInHouse: true,
    workstream: "Patch Management",
    activityLog: [
      { id: "log-008-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2025-12-15") },
      { id: "log-008-2", odiserId: "8", userName: "Robert Taylor", action: "was assigned as vulnerability owner", timestamp: new Date("2025-12-17") },
      { id: "log-008-3", odiserId: "8", userName: "Robert Taylor", action: "changed status", field: "status", oldValue: "Awaiting Disposition", newValue: "In Progress", timestamp: new Date("2025-12-20") },
      { id: "log-008-4", odiserId: "8", userName: "Robert Taylor", action: 'set disposition to "Fix"', field: "disposition", newValue: "Fix", timestamp: new Date("2025-12-20") },
      { id: "log-008-5", odiserId: "8", userName: "Robert Taylor", action: "changed status", field: "status", oldValue: "In Progress", newValue: "Pending Clear Scan", timestamp: new Date("2026-05-04") },
    ],
  },
  {
    id: "vuln-009",
    gisId: "GIS-2026-000009",
    qualysId: "QID-10009",
    cve: "CVE-2024-23334",
    title: "SSRF in Report Generation Module",
    status: "Awaiting Disposition",
    severity: "Medium",
    severityRisk: "Medium",
    cvssScore: 6.1,
    verificationStatus: "Pending Verification",
    source: "Rapid7",
    disposition: null,
    ctiRemediation: null,
    identifiedBlockers: [],
    hostName: "compliance-rpt-prd-003.bank.internal",
    fqdn: "compliance-rpt-prd-003.compliance.bank.internal",
    osName: "CentOS 7.9",
    osVersion: "7.9",
    ipAddresses: ["10.1.100.220"],
    operatingEnvironment: "Production",
    hostingPlatform: "On-Premise",
    isPublicInternetAccessible: false,
    isDmz: false,
    isOnSite: true,
    tier: "Tier 2 Important",
    securityZone: "Internal",
    applicationFullName: "Risk Reporting Platform",
    cioDisplayName: "Payments Technology",
    techExecutive: "John Smith",
    techExecutiveContact: "john.smith@bank.internal",
    vulnOwner: "Sarah Chen",
    vulnOwnerEmail: "sarah.chen@bank.internal",
    runbookOwner: "Security Operations",
    financialHierarchy: "Technology > Compliance > Reporting",
    description: "Server-side request forgery vulnerability in the report generation module allows attackers to make requests to internal services.",
    technicalDescription: "SSRF via URL parameter in report export.",
    technicalDetail: "User-supplied URL not validated before server request.",
    vulnerabilityFindings: "Confirmed via automated scan.",
    vulnerabilitySubcategory: "Injection",
    technology: "Docker",
    technologyVersion: "20.10.12",
    dateObserved: new Date("2025-11-25"),
    dateLastSeen: new Date("2026-05-07"),
    hostLastSeen: new Date("2026-05-08"),
    daysOpen: 170,
    dueDate: new Date("2026-05-22"),
    pastDue: false,
    patchCategory: "Security Update",
    patchTitle: "Report Generation Security Update",
    vendorRiskLevel: "Medium",
    gisExternalFlag: false,
    esmType: "Tier 2 Important",
    isBuiltInHouse: true,
    workstream: "Vulnerability Management",
    activityLog: [
      { id: "log-009-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2025-11-25") },
    ],
  },
  {
    id: "vuln-010",
    gisId: "GIS-2026-000010",
    qualysId: "QID-10010",
    cve: "CVE-2024-45519",
    title: "Template Injection in Email Rendering",
    status: "Resolved",
    severity: "Low",
    severityRisk: "Low",
    cvssScore: 3.7,
    verificationStatus: "Verified",
    source: "Qualys",
    disposition: "False Positive",
    ctiRemediation: false,
    identifiedBlockers: [],
    hostName: "email-notify-prd-002.bank.internal",
    fqdn: "email-notify-prd-002.notifications.bank.internal",
    osName: "Red Hat Enterprise Linux 8.6",
    osVersion: "8.6",
    ipAddresses: ["10.1.100.95"],
    operatingEnvironment: "Non-Production",
    hostingPlatform: "AWS",
    isPublicInternetAccessible: false,
    isDmz: false,
    isOnSite: false,
    tier: "Tier 3 Standard",
    securityZone: "Internal",
    applicationFullName: "Authentication Service",
    cioDisplayName: "Payments Technology",
    techExecutive: "Jane Doe",
    techExecutiveContact: "jane.doe@bank.internal",
    vulnOwner: "James Wilson",
    vulnOwnerEmail: "james.wilson@bank.internal",
    runbookOwner: "DevOps",
    financialHierarchy: "Technology > Notifications > Email",
    description: "Template injection vulnerability in the email rendering component allows attackers to execute arbitrary code.",
    technicalDescription: "Server-side template injection via email templates.",
    technicalDetail: "User input concatenated directly into template.",
    vulnerabilityFindings: "Initially flagged but determined to be false positive after investigation.",
    vulnerabilitySubcategory: "Injection",
    technology: "Kubernetes",
    technologyVersion: "1.23.4",
    dateObserved: new Date("2026-05-01"),
    dateLastSeen: new Date("2026-05-02"),
    hostLastSeen: new Date("2026-05-07"),
    daysOpen: 2,
    dueDate: new Date("2026-05-15"),
    remediatedDate: new Date("2026-05-03"),
    healthCheckComplete: true,
    healthCheckTime: new Date("2026-05-03"),
    pastDue: false,
    patchCategory: "None Required",
    patchTitle: "N/A - False Positive",
    vendorRiskLevel: "Low",
    gisExternalFlag: false,
    esmType: "Tier 3 Standard",
    isBuiltInHouse: true,
    workstream: "Vulnerability Management",
    activityLog: [
      { id: "log-010-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2026-05-01") },
      { id: "log-010-2", odiserId: "2", userName: "James Wilson", action: "was assigned as vulnerability owner", timestamp: new Date("2026-05-01") },
      { id: "log-010-3", odiserId: "2", userName: "James Wilson", action: 'set disposition to "False Positive"', field: "disposition", newValue: "False Positive", timestamp: new Date("2026-05-02") },
      { id: "log-010-4", odiserId: "2", userName: "James Wilson", action: "changed status", field: "status", oldValue: "Awaiting Disposition", newValue: "Resolved", timestamp: new Date("2026-05-03") },
    ],
  },
  {
    id: "vuln-011",
    gisId: "GIS-2026-000011",
    qualysId: "QID-10011",
    cve: "CVE-2025-21234",
    title: "Privilege Escalation via API Endpoint",
    status: "In Progress",
    severity: "High",
    severityRisk: "High",
    cvssScore: 8.0,
    verificationStatus: "Verified",
    source: "Qualys",
    disposition: "Fix",
    ctiRemediation: true,
    identifiedBlockers: [],
    crqNumber: "CRQ000082345678",
    hostName: "pay-proc-prd-006.bank.internal",
    fqdn: "pay-proc-prd-006.payments.bank.internal",
    osName: "Windows Server 2019",
    osVersion: "2019",
    ipAddresses: ["10.2.50.180"],
    operatingEnvironment: "Non-Production",
    hostingPlatform: "Azure",
    isPublicInternetAccessible: false,
    isDmz: false,
    isOnSite: false,
    tier: "Tier 1 Critical",
    securityZone: "Internal",
    applicationFullName: "Payments Gateway",
    cioDisplayName: "Payments Technology",
    techExecutive: "Robert Johnson",
    techExecutiveContact: "robert.johnson@bank.internal",
    vulnOwner: "Emily Johnson",
    vulnOwnerEmail: "emily.johnson@bank.internal",
    runbookOwner: "Security Operations",
    financialHierarchy: "Technology > Payments > Processing",
    description: "The API endpoint allows privilege escalation through improper authorization checks.",
    technicalDescription: "Missing authorization check on admin API endpoint.",
    technicalDetail: "Role-based access control bypassed via direct API call.",
    vulnerabilityFindings: "Confirmed via penetration testing.",
    vulnerabilitySubcategory: "Authorization",
    technology: "IBM MQ",
    technologyVersion: "9.2",
    dateObserved: new Date("2026-01-20"),
    dateLastSeen: new Date("2026-05-06"),
    hostLastSeen: new Date("2026-05-08"),
    daysOpen: 113,
    dueDate: new Date("2026-05-15"),
    expectedRemediationDate: new Date("2026-05-12"),
    requestedPatchWindow: "Sat 5/9 08:00–16:00 ET",
    pastDue: false,
    patchCategory: "Hotfix",
    patchTitle: "API Authorization Security Patch",
    vendorRiskLevel: "High",
    gisExternalFlag: false,
    esmType: "Tier 1 Critical",
    isBuiltInHouse: true,
    workstream: "Vulnerability Management",
    activityLog: [
      { id: "log-011-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2026-01-20") },
      { id: "log-011-2", odiserId: "5", userName: "Emily Johnson", action: "was assigned as vulnerability owner", timestamp: new Date("2026-01-22") },
      { id: "log-011-3", odiserId: "5", userName: "Emily Johnson", action: "changed status", field: "status", oldValue: "Awaiting Disposition", newValue: "In Progress", timestamp: new Date("2026-01-25") },
      { id: "log-011-4", odiserId: "5", userName: "Emily Johnson", action: 'set disposition to "Fix"', field: "disposition", newValue: "Fix", timestamp: new Date("2026-01-25") },
    ],
  },
  {
    id: "vuln-012",
    gisId: "GIS-2026-000012",
    qualysId: "QID-10012",
    cve: "CVE-2025-18765",
    title: "Improper Access Control in Customer Data",
    status: "Pending Clear Scan",
    severity: "Medium",
    severityRisk: "Medium",
    cvssScore: 5.9,
    verificationStatus: "Verified",
    source: "Qualys",
    disposition: "Fix",
    ctiRemediation: true,
    identifiedBlockers: [],
    crqNumber: "CRQ000084567890",
    remediationComplete: true,
    hostName: "crm-app-prd-001.bank.internal",
    fqdn: "crm-app-prd-001.crm.bank.internal",
    osName: "Ubuntu 20.04 LTS",
    osVersion: "20.04",
    ipAddresses: ["172.16.20.110"],
    operatingEnvironment: "Production",
    hostingPlatform: "AWS",
    isPublicInternetAccessible: false,
    isDmz: false,
    isOnSite: false,
    tier: "Tier 2 Important",
    securityZone: "Internal",
    applicationFullName: "Trade Settlement Engine",
    cioDisplayName: "Payments Technology",
    techExecutive: "Patricia Williams",
    techExecutiveContact: "patricia.williams@bank.internal",
    vulnOwner: "David Kim",
    vulnOwnerEmail: "david.kim@bank.internal",
    runbookOwner: "Platform Engineering",
    financialHierarchy: "Technology > CRM > Customer Data",
    description: "Improper access control allows unauthorized access to customer data through API endpoints.",
    technicalDescription: "IDOR vulnerability in customer data API.",
    technicalDetail: "Customer ID not validated against authenticated user.",
    vulnerabilityFindings: "Confirmed via code review.",
    vulnerabilitySubcategory: "Authorization",
    technology: "Oracle Database",
    technologyVersion: "19c",
    dateObserved: new Date("2026-02-10"),
    dateLastSeen: new Date("2026-05-01"),
    hostLastSeen: new Date("2026-05-07"),
    daysOpen: 87,
    dueDate: new Date("2026-05-29"),
    scheduledFixDate: new Date("2026-05-03"),
    remediatedDate: new Date("2026-05-03"),
    pastDue: false,
    patchCategory: "Security Update",
    patchTitle: "CRM Access Control Patch",
    vendorRiskLevel: "Medium",
    gisExternalFlag: false,
    esmType: "Tier 2 Important",
    isBuiltInHouse: true,
    workstream: "Patch Management",
    activityLog: [
      { id: "log-012-1", odiserId: "system", userName: "System", action: "Vulnerability detected and imported from scan", timestamp: new Date("2026-02-10") },
      { id: "log-012-2", odiserId: "4", userName: "David Kim", action: "was assigned as vulnerability owner", timestamp: new Date("2026-02-12") },
      { id: "log-012-3", odiserId: "4", userName: "David Kim", action: "changed status", field: "status", oldValue: "Awaiting Disposition", newValue: "In Progress", timestamp: new Date("2026-02-15") },
      { id: "log-012-4", odiserId: "4", userName: "David Kim", action: 'set disposition to "Fix"', field: "disposition", newValue: "Fix", timestamp: new Date("2026-02-15") },
      { id: "log-012-5", odiserId: "4", userName: "David Kim", action: "changed status", field: "status", oldValue: "In Progress", newValue: "Pending Clear Scan", timestamp: new Date("2026-05-03") },
    ],
  },
];
